const LongMessages = ({
    //about
    aboutTitle: 'The perfect match for you', 
    about: 'In matchmaking, trust us. We are here to help you find the partner that you deserve. We care for your relationship. Everyone need to love because of who they are not by how they look. Using our great algorithm, your interest and preference we look for matches that you desire. Because in IDo app your relationship is in good hands',
    title1: 'Everyone deserves to be love',
    title2: 'We find best for you', 
    title3: 'We ask questions', 
    description1: "No matter who you are, no matter what you're looking for, IDo helps you find meaningful connections",
    description2: "There are some things you should know before the date. On IDo, we help you find people that you're really suitable with.",
    description3: "We ask you questions about the things you care about.",
   
    
    //SafetyTips
    safetyTitle1: 'Online Safety',
    safetySubTitle1: 'Never Send Money or Share Financial Information',
    safetySubDescription1: "Never send money, especially over wire transfer, even if the person claims to be in an emergency. Wiring money is like sending cash — its nearly impossible to reverse the transaction or trace where the money went. Never share information that could be used to access your financial accounts. If another user asks you for money, report it to us immediately.",
    safetySubTitle2: 'Protect Your Personal Information',
    safetySubDescription2: "Never share personal information, such as your social security number, home or work address, or details about your daily routine (e.g., that you go to a certain gym every Monday) with people you don’t know. If you are a parent, limit the information that you share about your children on your profile and in early communications. Avoid sharing details such as your children’s names, where they go to school, or their ages or genders.",
    safetySubTitle3: 'Stay on the Platform',
    safetySubDescription3: "Keep your conversations on the IDo platform while you get to know your match. Because exchanges on IDo are subject to our Safe Message Filters (learn more here), users with bad intentions often try to move the conversation to text, messaging apps, email, or phone right away.",
    safetySubTitle4: 'Be Wary of Long Distance and Overseas Relationships',
    safetySubDescription4: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    safetySubTitle5: 'Report All Suspicious and Offensive Behavior',
    safetyBullet1: "You know when someone’s crossed the line and when they do, we want to know about it. Block and report anyone that violates our terms. Here are some examples of violations:",
    safetyBullet2: 'Requests for money or donations',
    safetyBullet3: 'Underage users',
    safetyBullet4: 'Harassment, threats, and offensive messages',
    safetyBullet5: 'Inappropriate or harmful behavior during or after meeting in person',
    safetyBullet6: 'Fraudulent profiles',
    safetyBullet7: 'Spam or solicitation including links to commercial websites or attempts to sell products or services',
    safetyBullet8: 'You can report any concerns about suspicious behavior from any profile page or messaging window or to support@IDo.com. For more information, check out our Community Guidelines.',
    safetySubTitle6: 'Protect Your Account',
    safetySubDescription6: "Be sure to pick a strong password, and always be careful when logging into your account from a public or shared computer. IDo will never send you an email asking for your username and password information — if you receive an email asking for account information, report it immediately.",

    safetyTitle2: 'Online Safety',
    safetySubTitle7: 'Never Send Money or Share Financial Information',
    safetySubDescription7: "Never send money, especially over wire transfer, even if the person claims to be in an emergency. Wiring money is like sending cash — its nearly impossible to reverse the transaction or trace where the money went. Never share information that could be used to access your financial accounts. If another user asks you for money, report it to us immediately.",
    safetySubTitle8: 'Protect Your Personal Information',
    safetySubDescription8: "Never share personal information, such as your social security number, home or work address, or details about your daily routine (e.g., that you go to a certain gym every Monday) with people you don’t know. If you are a parent, limit the information that you share about your children on your profile and in early communications. Avoid sharing details such as your children’s names, where they go to school, or their ages or genders.",
    safetySubTitle9: 'Stay on the Platform',
    safetySubDescription9: "Keep your conversations on the IDo platform while you get to know your match. Because exchanges on IDo are subject to our Safe Message Filters (learn more here), users with bad intentions often try to move the conversation to text, messaging apps, email, or phone right away.",
    safetySubTitle10: 'Be Wary of Long Distance and Overseas Relationships',
    safetySubDescription10: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    safetySubTitle11: 'Report All Suspicious and Offensive Behavior',
    safetySubDescription11: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    safetySubTitle12: 'Protect Your Account',
    safetySubDescription12: "Be sure to pick a strong password, and always be careful when logging into your account from a public or shared computer. IDo will never send you an email asking for your username and password information — if you receive an email asking for account information, report it immediately.",

    safetyTitle3: 'Online Safety',
    safetySubTitle13: 'Never Send Money or Share Financial Information',
    safetySubDescription13: "Never send money, especially over wire transfer, even if the person claims to be in an emergency. Wiring money is like sending cash — its nearly impossible to reverse the transaction or trace where the money went. Never share information that could be used to access your financial accounts. If another user asks you for money, report it to us immediately.",
    safetySubTitle14: 'Protect Your Personal Information',
    safetySubDescription14: "Never share personal information, such as your social security number, home or work address, or details about your daily routine (e.g., that you go to a certain gym every Monday) with people you don’t know. If you are a parent, limit the information that you share about your children on your profile and in early communications. Avoid sharing details such as your children’s names, where they go to school, or their ages or genders.",
    safetySubTitle15: 'Stay on the Platform',
    safetySubDescription15: "Keep your conversations on the IDo platform while you get to know your match. Because exchanges on IDo are subject to our Safe Message Filters (learn more here), users with bad intentions often try to move the conversation to text, messaging apps, email, or phone right away.",
    safetySubTitle16: 'Be Wary of Long Distance and Overseas Relationships',
    safetySubDescription16: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    safetySubTitle17: 'Report All Suspicious and Offensive Behavior',
    safetySubDescription17: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    
    contactName1: 'Philippine National Police Hotline',
    contactNum1: '117 or (02) 8722-0650',
    contactName2: 'VIOLENCE AGAINST WOMEN AND CHILDREN (VAWC) HOTLINES',
    contactSubName: 'Department of Social Welfare and Development',
    contactNum2: '(02) 8931-8101 to 07',
    contactName3: 'PNP-Women and Children Protection Center (WCPC)',
    contactNum3: '(02) 3410-3213',
    contactName4: 'NBI-Violence Against Women and Children Desk (VAWCD)',
    contactNum4: '(02) 8523-8231 to 38 | (02) 8525-6028',
    contactName5: 'Philippine Commission on Women (PCW)',
    contactNum5: 'Fax Number: (02) 8736-5249 | (02) 8736-7712 | (02) 8736-4449',

})