const LongMessages = ({
    //about
    aboutTitle: 'The perfect match for you', 
    about: 'In matchmaking, trust us. We are here to help you find the partner that you deserve. We care for your relationship. Everyone need to love because of who they are not by how they look. Using our great algorithm, your interest and preference we look for matches that you desire. Because in IDo app your relationship is in good hands',
    title1: 'Everyone deserves to be love',
    title2: 'We find best for you', 
    title3: 'We ask questions', 
    description1: "No matter who you are, no matter what you're looking for, IDo helps you find meaningful connections",
    description2: "There are some things you should know before the date. On IDo, we help you find people that you're really suitable with.",
    description3: "We ask you questions about the things you care about.",
    //privacy (guidelines)
    privacyTitle: 'IDo Privacy',
    priDes: 'This Privacy Policy explains the information that IDo Application (“IDo”) collects about users of the IDo mobile application and related website www.ido.com, how we use that information, and with whom we share it. If we make any material changes to our privacy policy, we will post a revised Privacy Policy on www.ido.com/privacy and on the privacy policy page within IDo. Changes to the Privacy Policy become effective the day they are posted on www.ido.com and/or posted within IDo, and that will constitute notification to users. Updates and changes may be made to the privacy policy when new versions of the app are released (i.e., IDo 0.0.1 etc.) If you have any questions, please contact us by sending an email to support@IDo.com',
    subtitle1: 'Information we collect',
    priDesMain1: 'Information collected automatically: When you use IDo App, or visit www.ido.com, we automatically collect and store information about your computer or mobile device and your activities. This information may include:',
    priDesDes1a: "Your mobile device's unique ID number;",
    priDesDes2a: "Your mobile device's geographic location while the app is actively running;",
    priDesDes3a: "Your computer's IP address;",
    priDesDes4a: "Technical information about your computer or mobile device (such as type of device, web browser or operating system);",
    priDesDes5a: "Your preferences and settings (time zone, language, privacy preferences, questionnaire, interest preferences, etc.);",
    priDesDes6a: "The buttons, controls and ads you clicked on (if any);",
    priDesDes7a: "How long you used IDo and which services and features you used; ",
    priDesDes8a: "And The online or offline status of IDo.",
    subtitle2: 'Information you choose to provide:',
    priDesMainParagraph1: 'In order to register, you will be asked to sign-in using your Facebook login. By allowing us to access your Facebook account, you understand that will have access to your name, gender, location, and pictures, as well as the names of your Facebook friends.',
    priDesMainParagraph2: 'Whenever you voluntarily disclose personal information on publicly viewable screens or pages, that information will be publicly available and can be collected and used by others. IDo cannot control and is not liable for whoever reads your posting or what other users may do with the information you voluntarily post, so we encourage you to exercise discretion and caution with respect to your personal information.',
    priDesMainParagraph3: 'You may also (but are not required to) provide information about yourself in your IDo profile. Any additional images or information you provide may be publicly displayed. If you wish, we will delete your account information. To do so, please close your account by sending an email to support@IDo.com.',
    subtitle3: 'How we use your information',
    priDesMain2: 'We use the information we collect to improve our services, make special offers to certain users, customize services for our users, better understand our users, diagnose and fix problems.',
    subtitle4: 'Geo-location-information',
    priDesMain3: "While IDo is in use, we keep track of your device’s geographic location so that we can connect you to other IDo users based on your particular geographic location. IDo does not track your location when you are not using the app.",
    subtitle5: 'Use of your information by others',
    bullet1: 'We may share user information with other companies for various reasons as described below. What information we make available to other companies depends on the nature of our relationships with them. We do not allow these companies to aggregate, sell, or disclose the user information we provide them in any way.',
    bullet2: 'Service Providers: We may share all the types of information we collect with vendors who provide services to us.',
    bullet3: "Analytics Companies: We allow analytics companies to use tracking technologies to collect information about our users' computers or mobile devices and their online activities. These companies analyze this information to help us understand how our sites and apps are being used. Analytics companies may use mobile device IDs, as described in the paragraph below (“Mobile device IDs”). Unlike cookies, device IDs cannot be deleted.",
    bullet4: "Mobile device IDs: In order to recognize you, store your preferences, and track your use of our application, we may store your mobile device IDs (the unique identifier assigned to a device by the manufacturer) when you use the IDo app.",
    bullet5: "WHAT WE DO NOT SHARE: We do not provide third parties with your name, address, email address, or phone number.",
    bullet6: "Aggregated Information: We may publicly disclose aggregated information about our users, such as the total number of our users and their overall demographics.",
    bullet7: "Legal matters: We may disclose any information in response to a legal request, such as a subpoena, court order, or government demand; to investigate or report illegal activity; or to enforce our rights or defend claims. We may also transfer your information to another company in connection with a corporate restructuring, such as a sale or merger.",
    subtitle6: "Children's privacy",
    priDesMain4: 'We do not allow persons under 18 to register for any service, and we do not knowingly collect any personally identifiable information from persons under the age of 18.',
    subtitle7: "Information from users outside the Philippines",
    priDesMain5: 'If you live outside the Philippines, or use IDo while traveling or living outside of the Philippines, your information will be sent to and stored in the Philippines, where our servers are located. By using IDo, you agree to the information collection, use, and sharing practices described in this Privacy Policy.',
    
    //SafetyTips
    safetyTitle1: 'Online Safety',
    safetySubTitle1: 'Never Send Money or Share Financial Information',
    safetySubDescription1: "Never send money, especially over wire transfer, even if the person claims to be in an emergency. Wiring money is like sending cash — its nearly impossible to reverse the transaction or trace where the money went. Never share information that could be used to access your financial accounts. If another user asks you for money, report it to us immediately.",
    safetySubTitle2: 'Protect Your Personal Information',
    safetySubDescription2: "Never share personal information, such as your social security number, home or work address, or details about your daily routine (e.g., that you go to a certain gym every Monday) with people you don’t know. If you are a parent, limit the information that you share about your children on your profile and in early communications. Avoid sharing details such as your children’s names, where they go to school, or their ages or genders.",
    safetySubTitle3: 'Stay on the Platform',
    safetySubDescription3: "Keep your conversations on the IDo platform while you get to know your match. Because exchanges on IDo are subject to our Safe Message Filters (learn more here), users with bad intentions often try to move the conversation to text, messaging apps, email, or phone right away.",
    safetySubTitle4: 'Be Wary of Long Distance and Overseas Relationships',
    safetySubDescription4: "Watch out for scammers who claim to be from your country but stuck somewhere else, especially if they ask for financial help to return home. Be wary of anyone who will not meet in person or talk on a phone/video call—they may not be who they say they are. If someone is avoiding your questions or pushing for a serious relationship without meeting or getting to know you first — that’s a red flag.",
    safetySubTitle5: 'Report All Suspicious and Offensive Behavior',
    safetyBullet1: "You know when someone’s crossed the line and when they do, we want to know about it. Block and report anyone that violates our terms. Here are some examples of violations:",
    safetyBullet2: 'Requests for money or donations',
    safetyBullet3: 'Underage users',
    safetyBullet4: '',
    safetyBullet5: '',
    safetyBullet6: '',
    safetyBullet7: '',
    safetyBullet8: '',
})