const fakeMessageOverviews = [
  {
    key: 0,
    profile_picture: require('../src/assets/samplePhotos/1.jpg'),
    latest_message: 'Guten Nacht!',
    name: 'Ashton',
    time: '1:30 pm',
    _id: '100',
  },
  {
    key: 1,
    profile_picture: require('../src/assets/samplePhotos/2.jpg'),
    latest_message: 'Tschuss!',
    name: 'Bruce',
    time: '12:30 pm',
    _id: '101',
  },
  {
    key: 2,
    profile_picture: require('../src/assets/samplePhotos/3.jpg'),
    latest_message: 'Bis bald!',
    name: 'Chowder',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 3,
    profile_picture: require('../src/assets/samplePhotos/1.jpg'),
    latest_message: 'Guten Morgen!',
    name: 'Digiorno',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 4,
    profile_picture: require('../src/assets/samplePhotos/2.jpg'),
    latest_message: 'Sie rittem um die wette mit dem steppenwind tausandmann',
    name: 'Eustace',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 5,
    profile_picture: require('../src/assets/samplePhotos/3.jpg'),
    latest_message: 'Guten Morgen!',
    name: 'France',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 6,
    profile_picture: require('../src/assets/samplePhotos/1.jpg'),
    latest_message: 'Guten Morgen!',
    name: 'Germany',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 7,
    profile_picture: require('../src/assets/samplePhotos/2.jpg'),
    latest_message: 'Guten Morgen!',
    name: 'Harold',
    time: '12:29 pm',
    _id: '102',
  },
  {
    key: 8,
    profile_picture: require('../src/assets/samplePhotos/3.jpg'),
    latest_message: 'Guten Morgen!',
    name: 'Indus',
    time: '12:29 pm',
    _id: '102',
  },
];

export default fakeMessageOverviews;
